### ISSUE TITLE
Using AutoEvents with a camera that is offline when device-camera-go starts up results in crash (nil pointer dereference)

### ISSUE THREAD

**Issue by siggiskulason** [edgexfoundry/device-camera-go#47]
The issue is that if autoevents have been defined using a onvif camera, and that camera is later offline when device-camera-go starts up, then device-camera will crash with a segfault when the autoevent runs.

1. Create a profile with a camera and autoevent
```
[[DeviceList]]
  Name = 'Camera001'
  Profile = 'camera'
  Description = 'Back garden camera'
  Location = 'back garden'
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
      Address = '192.168.1.103:8080'
 

[[DeviceList.AutoEvents]]
    Frequency = "30s"
    OnChange = false
    Resource = "onvif_snapshot"
```

2. Unplug camera, before starting up device-camera-go

3. Start up device-camera-go.

4. The initialisation step will fail to find the camera and initialize the ONVIF client
```
level=ERROR ts=2020-08-24T12:07:06.323658193Z app=device-camera-go source=onvifclient.go:43 msg="Error initializing ONVIF Client: Post \"http://192.168.1.103:8080/onvif/device_service\": dial tcp 192.168.1.103:8080: connect: no route to host"
```

4. The AutoEvent will run when scheduled, but   cause device-camera to crash with a segfault.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7e0016]

goroutine 85 [running]:
github.com/edgexfoundry-holding/device-camera-go/internal/driver.(*OnvifClient).GetSnapshot(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sidar/go/src/github.com/edgexfoundry/device-camera-go/internal/driver/onvifclient.go:111 +0x76
```
Note that this happens even if the camera has been used before and registered succesfully. All that is required is that it is not connected when device-camera-go is starting up.

The crash happens as  onvifClient is nil when the camera could not be initialized at device startup: 
https://github.com/edgexfoundry/device-camera-go/blob/c8688c583b3eeb3ad107f14a47c5424615149cea/internal/driver/driver.go#L178-L180

**Comment by siggiskulason** [comment]
I am preparing a pull request with a fix for this and will post that in a few days.
